version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces
      - node_modules:/workspaces/node_modules
    working_dir: /workspaces
    tty: true
volumes:
  node_modules:
